package hibernate;
// Generated Oct 1, 2016 8:58:28 PM by Hibernate Tools 5.2.0.Beta1

/**
 * Transactions generated by hbm2java
 */

public class Transactions implements java.io.Serializable {

	private int id;
	private String date;
	private Double amount;
	
	
	public Transactions() {
	}

	public Transactions(int id) {
		this.id = id;
	}

	public Transactions(int id, String date, Double amount) {
		this.id = id;
		this.date = date;
		this.amount = amount;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	public Double getAmount() {
		return this.amount;
	}

	public void setAmount(Double amount) {
		this.amount = amount;
	}

}
